version: '3'
services:
  wordpress-mysql:
    image: 'wordpress-mysql:local-latest'
    build:
      context: '.'
      dockerfile: 'docker/mysql/Dockerfile'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
  wordpress-apache:
    image: 'wordpress-apache:local-latest'
    build:
      context: '.'
      dockerfile: 'docker/apache/Dockerfile'
    ports:
      - 80:80
    volumes:
       - ./StylaMagazine:/home/root/StylaMagazine
    depends_on:
      - wordpress-mysql
